### ISSUE TITLE
preferred starter kit for the final project

### ISSUE THREAD

**Issue by yipcma** [bradwestfall/CSS-Tricks-React-Series#6]
Would love to build the final project in guide 3 from scratch without using the code in the repo. Which start kit would you recommend for such undertaking?

Thanks a lot for the wonderful guide. It makes the redux bit much clearer in my head.

**Comment by yipcma** [comment]
Also, which one would you usually use for your projects?

**Comment by bradwestfall** [comment]
Actually I don't have so much a go-to that I use. Besides if you went with someone's starter code, they might take a whole different approach that doesn't blend as well with the code I wrote. I've noticed that since JS is so expressive and with React having so many different facilitator tools, there are many approaches. But have you considered trying to make the guide-3 as much as possible without glancing at the code. See how far you can go between glances?

**Comment by yipcma** [comment]
@bradwestfall  thanks for the tip. I'm just worried about the gulp/webpack bits so would like some recommendations of how to build something from scratch. Any suggestion on that?

**Comment by bradwestfall** [comment]
@yipcma  I don't think you need to know how to write that stuff from scratch (at first). With webpack you'll likely start your second project by referring to what you did on the first project and mostly copying the config over. And starting new projects for most is a seldom thing, so I don't know how valuable it is to know how to set that up from scratch. I would focus more on learning what the parts do, and that can be done my looking at other's configs and looking things up in docs. Pretty much the same story for Gulp. If you do start multiple projects over and over you'll start to naturally pick up how to write it from scratch I think
